version: 2

project_name: crd-explorer

changelog:
  use: github
  sort: desc
  filters:
    exclude:
      - '^Merge pull request'
      - '^build(release): bump brew formula'
  groups:
    - title: "Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "Documentation Updates"
      regexp: '^.*?chore\(docs\)(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: "Other Changes"
      regexp: "^(ci|build|misc|perf|deps):"
      order: 3
    - title: "Miscellaneous"
      regexp: ".*"
      order: 4

before:
  hooks:
    - go fmt ./...
    - go mod tidy
    - go mod download

builds:
  - id: crd-explorer
    main: .
    binary: crd-explorer
    env:
      - CGO_ENABLED=0
    ldflags: -s -w -X github.com/pehlicd/crd-explorer/cmd.versionString={{ .Tag }} -X github.com/pehlicd/crd-explorer/cmd.buildDate={{ .Date }} -X github.com/pehlicd/crd-explorer/cmd.buildCommit={{ .Commit }}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

  - id: kubectl-crd-explorer
    main: .
    binary: kubectl-crd_explorer
    env:
      - CGO_ENABLED=0
    ldflags: -s -w -X github.com/pehlicd/crd-explorer/cmd.versionString={{ .Tag }} -X github.com/pehlicd/crd-explorer/cmd.buildDate={{ .Date }} -X github.com/pehlicd/crd-explorer/cmd.buildCommit={{ .Commit }}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - id: crd-explorer-archive
    ids:
      - crd-explorer
    name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: false
    formats: ['tar.gz']
    files:
      - LICENSE

  - id: kubectl-crd-explorer-archive
    ids:
      - kubectl-crd-explorer
    name_template: "kubectl-crd_explorer_{{ .Tag }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: false
    formats: ['tar.gz']
    files:
      - LICENSE

release:
  github:
    name: crd-explorer
    owner: pehlicd
  draft: false
