name: helm-lint
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  helm-lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: helm-lint
        run: make lint-helm
